modLoader="javafml"
loaderVersion="[28,)"
#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="mikesmod"
version="1.0.0"
displayName="Mikes Mod"
#updateJSONURL="http://myurl.me/"
displayURL="http://mikemcmillan.dev"
#logoFile="examplemod.png"
description='''
Mike's mod playground
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"